export const champStatCode = {
  hp: 'hp',
  hpperlevel: 'hpperlevel',
  mp: 'mp',
  mpperlevel: 'mpperlevel',
  movespeed: 'movespeed',
  armor: 'armor',
  armorperlevel: 'armorperlevel',
  spellblock: 'spellblock',
  spellblockperlevel: 'spellblockperlevel',
  attackrange: 'attackrange',
  hpregen: 'hpregen',
  hpregenperlevel: 'hpregenperlevel',
  mpregen: 'mpregen',
  mpregenperlevel: 'mpregenperlevel',
  crit: 'crit',
  critperlevel: 'critperlevel',
  attackdamage: 'attackdamage',
  attackdamageperlevel: 'attackdamageperlevel',
  attackspeedperlevel: 'attackspeedperlevel',
  attackspeed: 'attackspeed',
};
